### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by nickhamze**
Adding screenshots

### CODE REVIEW

**Comment by jrtashjian** [comment]
I'm only seeing readme updates, do you have screenshots to add as well?

**Comment by nickhamze** [comment]
Yeah I have all the screenshots and asset files. I was just going to upload them to SVN so I wasn't going to add them to the repo. Should we keep them here too? I can send them to you.

**Comment by nickhamze** [comment]
Yeah I have all the screenshots and asset files. I was just going to upload them to SVN so I wasn't going to add them to the repo. Should we keep them here too? I can send them to you.

**Comment by jrtashjian** [comment]
Yeah, they should be in the repo anyway. Add them here and I can get them added so they can be pushed to SVN with everything else.

**Comment by nickhamze** [comment]
Here they are. The banner and icon are there too: https://www.dropbox.com/sh/qa5b5ytasg6pkq2/AADuwLmIcUF1FjBkl2XBusM3a?dl=0

**Pull request closed without merging**
